name: xMake CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup xMake
      uses: xmake-io/github-action-setup-xmake@v1
    - name: Create Packagee with xMake
      run: |
        xmake package
      working-directory: ${{ github.workspace }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: skyrimdirectionalcombat
        path: build/packages
