name: xMake CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup xMake
      uses: xmake-io/github-action-setup-xmake@v1
    - name: Build Projct
    - run: |
        xmake
    - name: Create Package with xMake
      run: |
        xmake package
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: skyrimdirectionalcombat
        path: build/packages
